version: '3.4'

services:
    redis:
        image: 'redis'

    worker:
        build:
            context: '.'
        command: celery worker -A etsms.app -B
        depends_on: 
            - 'redis'